//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalServiceDetail
    {
        public int AdditionalServiceDID { get; set; }
        public Nullable<int> AdditionalServiceID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string TruckNo { get; set; }
        public string ContainerNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> LabourContractorID { get; set; }
        public Nullable<decimal> PerUnitCharges { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
    }
}
