//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_StockRegister
    {
        public int StockRagisterID { get; set; }
        public Nullable<int> WareHouseID { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> InwardDate { get; set; }
        public Nullable<int> ReferanceNo { get; set; }
        public Nullable<int> InwardDID { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> StorageAreaTypeID { get; set; }
        public Nullable<int> StorageAreaID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string ItemsInPacket { get; set; }
        public Nullable<decimal> InQuantity { get; set; }
        public Nullable<decimal> DOQuantity { get; set; }
        public Nullable<decimal> OutQuantity { get; set; }
        public Nullable<decimal> BalanceQuantity { get; set; }
        public Nullable<decimal> TotalOutQuantity { get; set; }
        public Nullable<int> ProcessTypeID { get; set; }
        public Nullable<decimal> AreaOccupied { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<bool> IsCustomerArea { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<decimal> OpeningQuantity { get; set; }
        public Nullable<int> InwardLocationID { get; set; }
    }
}
