//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallanDetail
    {
        public int ChallanDID { get; set; }
        public Nullable<int> ChallanID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string ItemsInPacket { get; set; }
        public Nullable<decimal> ChallanQuantity { get; set; }
        public Nullable<decimal> DamageQuantity { get; set; }
        public Nullable<decimal> InQuantity { get; set; }
        public Nullable<decimal> DifferanceQuantity { get; set; }
        public Nullable<System.DateTime> MFGDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string LotNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> LabourContractorID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> StorageAreaTypeID { get; set; }
    }
}
