//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallanLocation
    {
        public int ChallanLocationID { get; set; }
        public Nullable<int> ChallanDID { get; set; }
        public Nullable<decimal> StorageQuantity { get; set; }
        public Nullable<int> StorageAreaID { get; set; }
        public Nullable<bool> IsCustomerAreaSelected { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
