//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListDetail
    {
        public int CheckListDetailID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> StorageAreaID { get; set; }
        public Nullable<int> CheckListID { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public string OptionValue { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual CheckListMaster CheckListMaster { get; set; }
    }
}
