//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckListMaster()
        {
            this.CheckListDetails = new HashSet<CheckListDetail>();
        }
    
        public int CheckListID { get; set; }
        public string CheckListName { get; set; }
        public string Description { get; set; }
        public Nullable<int> PeriodTypeID { get; set; }
        public Nullable<int> Frequancy { get; set; }
        public Nullable<bool> IsOptional { get; set; }
        public Nullable<bool> OptionYesNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListDetail> CheckListDetails { get; set; }
    }
}
