//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractDetail
    {
        public int ContractDID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<int> RateListID { get; set; }
        public Nullable<System.DateTime> WefDate { get; set; }
        public Nullable<System.DateTime> WetDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual CustomerContract CustomerContract { get; set; }
    }
}
