//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_Demo
    {
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string Initials { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> CityID { get; set; }
        public string EmailID { get; set; }
        public string GSTINNo { get; set; }
        public string PANNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
