//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContact
    {
        public int CustomerContactID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ContactPersonName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public string MobileNo { get; set; }
        public string ContactNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<bool> SendSMS { get; set; }
        public Nullable<bool> SendEmail { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
    }
}
