//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerParty
    {
        public int CustomerPartyID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string PartyName { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingAddress1 { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }


    public class cls_DeliveryOrderParty
    {
        public int CustomerID { get; set; }
        public int WarehouseID { get; set; }
        public int FinancialYearID { get; set; }
        public int UserID { get; set; }
        public int DeliveryOrderID { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
    }
}
