//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLogInHistory
    {
        public int LoginID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string CustomerLoginID { get; set; }
        public string LoginIP { get; set; }
        public string SessionID { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string Source { get; set; }
    }
}
