//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryOrder
    {
        public int DeliveryOrderID { get; set; }
        public string DeliveryOrderNo { get; set; }
        public Nullable<System.DateTime> DeliveryOrderDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> WareHouseID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string DeliverTo { get; set; }
        public Nullable<int> CustomerPartyID { get; set; }
        public string ShippingAddress { get; set; }
        public string OrderGivenBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> StatusID { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<int> ByCustomer { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string TruckNo { get; set; }
        public string ContainerNo { get; set; }
    }
}
