//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchDetail
    {
        public int DispatchDID { get; set; }
        public Nullable<int> DispatchID { get; set; }
        public Nullable<int> DeliveryOrderDID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> InwardDID { get; set; }
        public string LotNo { get; set; }
        public Nullable<decimal> DispatchQuantity { get; set; }
        public Nullable<int> InwardLocationID { get; set; }
        public Nullable<int> StorageAreaID { get; set; }
    }
}
