//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch
    {
        public int DispatchID { get; set; }
        public string DispatchNo { get; set; }
        public Nullable<int> WareHouseID { get; set; }
        public Nullable<int> DeliveryOrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CustomerPartyID { get; set; }
        public string ShippingAddress { get; set; }
        public string OrderGivenBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string TruckNo { get; set; }
        public string ContainerNo { get; set; }
    }
}
