//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_report
    {
        public int EmailReportID { get; set; }
        public string EmailReportName { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string ReportID { get; set; }
        public Nullable<bool> Today { get; set; }
        public Nullable<bool> Daily { get; set; }
        public Nullable<bool> Weekly { get; set; }
        public string Weekly_day { get; set; }
        public Nullable<bool> Monthly { get; set; }
        public Nullable<int> Monthly_day { get; set; }
        public Nullable<System.TimeSpan> EmailTime { get; set; }
        public string EmailSubject { get; set; }
        public string EmailText { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
