//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exception
    {
        public int ExceptionID { get; set; }
        public string Error_Message { get; set; }
        public string Error_Procedure { get; set; }
        public Nullable<int> Error_State { get; set; }
        public Nullable<int> Error_Severity { get; set; }
        public Nullable<int> Error_Number { get; set; }
    }
}
