//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export
    {
        public int ExportID { get; set; }
        public string ExportNo { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public string TruckNo { get; set; }
        public string ContainerNo { get; set; }
        public Nullable<decimal> ExportCharges { get; set; }
        public Nullable<int> LabourContractorID { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public string CancelledRemarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
