//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAddonService
    {
        public int InvoiceAddonServiceID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> AddOnServiceID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> BillingCycleID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> BillingCycleQuantity { get; set; }
        public Nullable<decimal> AddonServiceCharges { get; set; }
        public Nullable<int> FinancialYearID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public string HSNCode { get; set; }
    }
}
