//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTax
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceTax()
        {
            this.InvoiceTaxDetails = new HashSet<InvoiceTaxDetail>();
        }
    
        public int InvoiceTaxID { get; set; }
        public int InvoiceID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string HCNCode { get; set; }
        public Nullable<decimal> ServiceAmount { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceTaxDetail> InvoiceTaxDetails { get; set; }
    }
}
