//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTaxDetail
    {
        public int InvoiceTaxDID { get; set; }
        public int InvoiceTaxID { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<int> TaxTypeID { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
    
        public virtual InvoiceTax InvoiceTax { get; set; }
    }
}
