//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLabour
    {
        public int InvoiceLabourID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> InwardDID { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> LabourContractorID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> BillingCycleID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Rate_L { get; set; }
        public Nullable<decimal> LabourCharges { get; set; }
        public Nullable<decimal> LabourCharges_L { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<int> ReferanceNo { get; set; }
        public string Description { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public string HSNCode { get; set; }
        public Nullable<int> FinancialYearID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CustomerRateListID { get; set; }
    }
}
