//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inward
    {
        public int InwardID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> WareHouseID { get; set; }
        public Nullable<System.DateTime> InwardDate { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<System.DateTime> BillingStartDate { get; set; }
        public string PersonName { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DocID { get; set; }
        public Nullable<int> UnLoadingBy { get; set; }
        public Nullable<int> TransferID { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<int> FinancialYearID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
