//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InwardDetail
    {
        public int InwardDID { get; set; }
        public Nullable<int> InwardID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string LotNo { get; set; }
        public string FirstLotNo { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string ItemsInPacket { get; set; }
        public Nullable<decimal> InQuantity { get; set; }
        public Nullable<decimal> OutQuantity { get; set; }
        public Nullable<decimal> InprocessQuantity { get; set; }
        public Nullable<decimal> BalanceQuantity { get; set; }
        public Nullable<System.DateTime> MFGDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<int> SelfLife { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TransferDID { get; set; }
        public Nullable<int> LabourContractorID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> StorageAreaTypeID { get; set; }
        public Nullable<int> ChallanDID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Country { get; set; }
    }
}
