//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InwardLocation
    {
        public int InwardLocationID { get; set; }
        public Nullable<int> InwardDID { get; set; }
        public Nullable<int> StorageAreaID { get; set; }
        public Nullable<decimal> StorageQuantity { get; set; }
        public Nullable<decimal> DOQuantity { get; set; }
        public Nullable<decimal> OutQuantity { get; set; }
        public Nullable<decimal> BalanceQuantity { get; set; }
        public string LotNo { get; set; }
        public Nullable<decimal> AreaOccupied { get; set; }
        public Nullable<bool> IsCustomerAreaSelected { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string InwardRemarks { get; set; }
    }
}
