//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InwardTrasport
    {
        public int InwardTransPortID { get; set; }
        public string TransporterName { get; set; }
        public string TruckNo { get; set; }
        public string ContainerNo { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> InwardDID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    }
}
