//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotStock
    {
        public int StockID { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> InwardDID { get; set; }
        public Nullable<decimal> InQuantity { get; set; }
        public Nullable<decimal> DOQuantity { get; set; }
        public Nullable<decimal> OutQuantity { get; set; }
        public Nullable<decimal> BalanceQuantity { get; set; }
    }
}
