//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaxNumber
    {
        public int ID { get; set; }
        public Nullable<int> MaxID { get; set; }
        public string DocumentType { get; set; }
        public string Prefix { get; set; }
        public string Sufix { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> FinancialYearID { get; set; }
        public string FinancialYear { get; set; }
        public Nullable<int> StorageAreaMasterID { get; set; }
    }
}
