//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTemplate
    {
        public int MessageTemplateID { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public string MessageTemplate1 { get; set; }
        public Nullable<bool> MobileSMS { get; set; }
        public Nullable<bool> MobileApp { get; set; }
        public Nullable<bool> WebSite { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
