//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageApp
    {
        public int MessageAppID { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<int> ReferanceID { get; set; }
        public string Message { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string MobileNo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusUpdateDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
