//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutWard
    {
        public int OutWardID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string OutWardNo { get; set; }
        public Nullable<System.DateTime> OutWardDate { get; set; }
        public Nullable<System.DateTime> BillStartDate { get; set; }
        public Nullable<int> DispatchID { get; set; }
        public Nullable<int> DeliveryOrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CustomerPartyID { get; set; }
        public Nullable<int> DocID { get; set; }
        public Nullable<int> LoadingBy { get; set; }
        public string TruckNo { get; set; }
        public string ContainerNo { get; set; }
        public string TransporterName { get; set; }
        public string DriverName { get; set; }
        public string DriverNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TransferID { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
