//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutwardDetail
    {
        public int OutwardDID { get; set; }
        public Nullable<int> OutWardID { get; set; }
        public Nullable<int> DispatchDID { get; set; }
        public Nullable<int> DeliveryOrderDID { get; set; }
        public Nullable<decimal> OutQuantity { get; set; }
        public Nullable<int> LabourContractorID { get; set; }
    }
}
