//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutwardCharge
    {
        public int OutwardChargeID { get; set; }
        public int OutwardDID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> L_Rate { get; set; }
    }
}
