//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessService
    {
        public int ProcessServiceID { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<bool> IsOptional { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Process Process { get; set; }
        public virtual Service Service { get; set; }
    }
}
