//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTaxDetail
    {
        public int ProductTaxID { get; set; }
        public Nullable<System.DateTime> WefDate { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> StorageTypeID { get; set; }
        public string HSNCode { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
