//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> ProductGroupID { get; set; }
        public int PackingTypeID { get; set; }
        public Nullable<int> UOMID { get; set; }
        public string ItemUnit { get; set; }
        public int ItemCount { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> ProductTaxCategoryID { get; set; }
        public Nullable<int> TemperatureCategoryID { get; set; }
        public Nullable<decimal> WeightinKG { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> CubicArea { get; set; }
        public Nullable<int> SelfLife { get; set; }
        public Nullable<int> ApproxValue { get; set; }
        public Nullable<int> BillingcycleID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual UOM UOM { get; set; }
    }
}
