//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTaxCategory
    {
        public int ProductTaxCategoryID { get; set; }
        public Nullable<System.DateTime> WefDate { get; set; }
        public string ProductTaxCategory1 { get; set; }
        public Nullable<int> TaxID { get; set; }
        public string HCNCode { get; set; }
        public Nullable<int> ServiceID { get; set; }
    }
}
