//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateList
    {
        public int RateListID { get; set; }
        public Nullable<int> RateID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> L_Rate { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<int> BillingCycleID { get; set; }
        public Nullable<System.DateTime> WefDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual BillingCycle BillingCycle { get; set; }
        public virtual Rate Rate1 { get; set; }
        public virtual Service Service { get; set; }
    }
}
