//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public int ReceiptDID { get; set; }
        public Nullable<int> ReceiptID { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TDSAmount { get; set; }
        public string ReferenceNo { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsCleared { get; set; }
        public Nullable<int> ReceiptInvoiceID { get; set; }
    
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
