//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptInvoiceDetail
    {
        public int ReceiptInvoiceID { get; set; }
        public Nullable<int> ReceiptID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public Nullable<decimal> TDSAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
    
        public virtual Receipt Receipt { get; set; }
    }
}
