//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepackingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RepackingDetail()
        {
            this.RepackingCharges = new HashSet<RepackingCharge>();
        }
    
        public int RepackingDID { get; set; }
        public Nullable<int> RepackingID { get; set; }
        public Nullable<int> InwardDID { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> InwardLocationID { get; set; }
        public Nullable<int> StorageAreaID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> NewProductID { get; set; }
        public Nullable<decimal> NewQuantity { get; set; }
        public Nullable<int> NewBrandID { get; set; }
        public Nullable<int> NewCountinPacket { get; set; }
        public Nullable<int> NewStorageAreaID { get; set; }
        public Nullable<int> LabourContractorID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> NewStorageAreaTypeID { get; set; }
    
        public virtual Repacking Repacking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepackingCharge> RepackingCharges { get; set; }
    }
}
