//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public string ReportName { get; set; }
        public string DisplayName { get; set; }
        public byte[] ReportBuffer { get; set; }
        public string ReportType { get; set; }
        public string SPName { get; set; }
        public string KeyColumn { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public Nullable<bool> P_Customer { get; set; }
        public Nullable<bool> P_FromAndToDate { get; set; }
        public Nullable<bool> P_AsOnDate { get; set; }
        public Nullable<bool> P_LotNo { get; set; }
        public Nullable<bool> P_Product { get; set; }
        public Nullable<bool> P_Brand { get; set; }
        public Nullable<bool> P_StorageArea { get; set; }
        public Nullable<bool> P_LabourContractors { get; set; }
        public Nullable<bool> P_UserName { get; set; }
        public Nullable<bool> ExportReport { get; set; }
        public Nullable<bool> PrintReport { get; set; }
        public string PrinterName { get; set; }
        public string PageSize { get; set; }
        public string Oriantation { get; set; }
        public Nullable<decimal> TopMargin { get; set; }
        public Nullable<decimal> LeftMargin { get; set; }
        public Nullable<decimal> BottomMargin { get; set; }
        public Nullable<decimal> RightMargin { get; set; }
        public Nullable<bool> email_report { get; set; }
        public Nullable<bool> P_CustomerGroup { get; set; }
        public Nullable<bool> P_InvoiceType { get; set; }
    }
}
