//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleUI
    {
        public int RoleUIID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> UIMasterID { get; set; }
        public Nullable<bool> New_flg { get; set; }
        public Nullable<bool> List_flg { get; set; }
        public Nullable<bool> Edit_flg { get; set; }
        public Nullable<bool> Delete_flg { get; set; }
        public Nullable<bool> Print_flg { get; set; }
        public Nullable<bool> Export_flg { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
