//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShiftingDetail()
        {
            this.ShiftingCharges = new HashSet<ShiftingCharge>();
        }
    
        public int ShiftingDID { get; set; }
        public Nullable<int> ShiftingID { get; set; }
        public Nullable<int> InwardDID { get; set; }
        public Nullable<int> InwardLocationID { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> FromLocationID { get; set; }
        public Nullable<int> ToLocationID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> LabourContractorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftingCharge> ShiftingCharges { get; set; }
    }
}
