//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSNotification
    {
        public int SMSNotificationID { get; set; }
        public Nullable<int> warehouseID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ReferanceNo { get; set; }
        public string process { get; set; }
        public string MobileNo { get; set; }
        public string SMS { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Response { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
