//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCheckingDetail
    {
        public int StockCheckingDID { get; set; }
        public Nullable<int> StockCheckingID { get; set; }
        public Nullable<int> InwardDID { get; set; }
        public Nullable<int> InwardLocationID { get; set; }
        public int StorageAreaID { get; set; }
        public string LotNo { get; set; }
        public Nullable<decimal> StockQuantity { get; set; }
        public Nullable<decimal> ExtraQuantity { get; set; }
        public Nullable<decimal> LessQuantity { get; set; }
        public string Remarks { get; set; }
        public string Action { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
