//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopDeliveryOrder
    {
        public int StopDeliveryID { get; set; }
        public Nullable<int> WaherhouseID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Release { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ReleasRemarks { get; set; }
        public Nullable<int> ReleaseBy { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    }
}
