//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageTransaction
    {
        public int StorageTransactionID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> StorageAreaID { get; set; }
        public Nullable<decimal> OccupiedArea { get; set; }
        public Nullable<int> StockRegisterID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
