//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageOccupancy
    {
        public int StorageOccupancyID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<System.DateTime> ForTheDay { get; set; }
        public Nullable<int> StorageAreaID { get; set; }
        public Nullable<int> NoofItems { get; set; }
        public Nullable<decimal> AreaOcupied { get; set; }
        public Nullable<decimal> AvailableArea { get; set; }
        public Nullable<decimal> AreaSize { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
