//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssetup
    {
        public int IDNo { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<bool> Inward_ShowserviceCharges { get; set; }
        public Nullable<bool> Inward_ServicechargesEditable { get; set; }
        public Nullable<bool> Inward_ChallanEnable { get; set; }
        public Nullable<bool> Inward_showLotNo { get; set; }
        public Nullable<bool> Outward_ShowserviceCharges { get; set; }
        public Nullable<bool> Outward_ServicechargesEditable { get; set; }
        public Nullable<bool> Invoice_SingleInvoice { get; set; }
    }
}
