//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxDetail
    {
        public int TaxDID { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<int> TaxTypeID { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<System.DateTime> WefDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
