//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transfer()
        {
            this.TransferDetails = new HashSet<TransferDetail>();
        }
    
        public int TransferID { get; set; }
        public string TransferNo { get; set; }
        public Nullable<int> WareHouseID { get; set; }
        public Nullable<int> FromCustomerID { get; set; }
        public Nullable<int> ToCustomerID { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string OrderGivenBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferDetail> TransferDetails { get; set; }
    }
}
