//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransferDetail()
        {
            this.TransferCharges = new HashSet<TransferCharge>();
        }
    
        public int TransferDID { get; set; }
        public Nullable<int> TransferID { get; set; }
        public Nullable<int> InwardDID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> InwardLocationID { get; set; }
        public Nullable<int> StorageAreaID { get; set; }
        public Nullable<decimal> TransferQuantity { get; set; }
        public Nullable<int> ToStorageAreaID { get; set; }
        public int LabourContractorID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> StorageAreaTypeID { get; set; }
    
        public virtual Transfer Transfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferCharge> TransferCharges { get; set; }
    }
}
