//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_WebAPI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Update_Outward
    {
        public int Update_OutwardID { get; set; }
        public Nullable<int> OutwardID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> DockID { get; set; }
        public string TruckNo { get; set; }
        public string ContainerNo { get; set; }
        public Nullable<int> LoadingBy { get; set; }
        public Nullable<System.DateTime> CustomerPartyID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> LabourContractorID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
